bridge:
    image: openethereum/openethereum:latest
    command: --chain ropsten --cache-size 512 --pruning fast --warp --ui-interface all --jsonrpc-interface all --unsafe-expose --ws-interface all --ws-origins all
    ports:
        - "8180:8180"
        - "8545:8545"
        - "8546:8546"
        - "30303:30303"
        - "30303:30303/udp"

    image: vdexbridge:latest
    entrypoint: "bash -c \"\ 
                node bridge-test/test/test1/quaremachina.js\
    \""
    ports:
        - "8180:8180"
        - "8545:8545"
        - "8546:8546"
        - "30303:30303"
        - "30303:30303/udp"     